### ISSUE TITLE
Target Selection

### ISSUE THREAD

**Issue by Gerzer** [devMEremenko/XcodeBenchmark#1]
Thanks for creating this! I look forward to seeing the benchmarks on the Max Tech YouTube channel. There's just one issue, though: you might want to provide instructions in the README about how to select the correct target. When I first opened the Xcode workspace myself, it defaulted to the `FirebaseRemoteConfig` target, which seems like the wrong one.

More generally, the UI in Xcode 12 beta is fairly different from that in Xcode 11, so once the Xcode 12 GM is released later this year, you might want to update the instructions.

**Comment by Gerzer** [comment]
Never mind; I just misread the instructions. That's my fault! Regardless, my point about Xcode 12 still stands.

**Comment by devMEremenko** [comment]
Hi @Gerzer,

CocoaPods schemes were hidden. 
There is only one active scheme now - `XcodeBenchmark`.

Thank you for raising this. 
Let me know if it works for you.
