### ISSUE TITLE
why my m1 macbookair took so long?

### ISSUE THREAD

**Issue by Merlini93** [devMEremenko/XcodeBenchmark#123]
I test for more than 10 times,but still took me more than 220s,what's wrong with my macbook air?
<img width="894" alt="截屏2021-02-06 23 47 44" src="https://user-images.githubusercontent.com/11328707/107122957-d40ee200-68d5-11eb-9f7c-8f9ea8c60409.png">

**Comment by KeiroMidori** [comment]
I get similar results with macOS 11.2 and Xcode 12.3 on a Mac Mini M1 16gb 512ssd. I think the latest macOS version may slow down xcode builds.

**Comment by Merlini93** [comment]
> I get similar results with macOS 11.2 and Xcode 12.3 on a Mac Mini M1 16gb 512ssd. I think the latest macOS version may slow down xcode builds.
> 
> EDIT: I guess we just have to wait for more people to share their benchmarks on 11.2 to see if that's isolated or not

Try to use Terminal instead of iTerm, It only took me 130s.

**Comment by KeiroMidori** [comment]
Indeed. Thanks
