### ISSUE TITLE
Build completes within seconds in xcode12

### ISSUE THREAD

**Issue by cielo** [devMEremenko/XcodeBenchmark#20]
Hello,

I am unsure if this is happening due to recent changes in xcode12. If I press Build hotkey, the build completes within a matter of seconds. This is after cleaning up all derived folders.

While the build completes within a sec or two, the Indexing process continues for a while.

Is there a way to properly measure build time with the newer version of Xcode 12?

**Comment by devMEremenko** [comment]
Hi @cielo,

Please make sure that `XcodeBenchmark` -> `Any iOS Device` pair is selected at the top left corner.

**Comment by cielo** [comment]
Yes I selected that option. The build completes less than 0.1s or so.

If I clean a build folder ('Product' - 'Clean Build Folder' option), the build time increases to 2~3 sec again for the first run, but again falls back to 0.1s.

**Comment by radianttap** [comment]
The project currently does not even compile of Xcode 12.

**Comment by devMEremenko** [comment]
Hi all,

Thank you for your efforts.

XcodeBenchmark has been just updated to support Xcode 12 and running from `Terminal` (see updated [ReadMe](https://github.com/devMEremenko/XcodeBenchmark))

Could you please rerun your tests with the latest version of XcodeBenchmark and ensure you attached all necessary information described in the [Contribution](https://github.com/devMEremenko/XcodeBenchmark#contribution) section.

Thanks

**Comment by devMEremenko** [comment]
I am closing this PR. Feel free to reopen it if the latest version of XcodeBenchmark does not work for you.
