### ISSUE TITLE
Xcode 12.0.1 fails to build Eureka dependency

### ISSUE THREAD

**Issue by valeriyvan** [devMEremenko/XcodeBenchmark#22]
<img width="1512" alt="Screenshot 2020-10-16 at 23 44 34" src="https://user-images.githubusercontent.com/1630974/96311410-af7eb980-1009-11eb-917c-392a27e2e0b2.png">

**Comment by Pe-te** [comment]
Same here, Xcode 12.1 (12A7403):
> Error Group
Segmentation fault: 11
Uncategorized Group
Command CompileSwift failed with a nonzero exit code

**Comment by owenzhao** [comment]
The same with Xcode 12.2.

**Comment by devMEremenko** [comment]
Hi all,

XcodeBenchmark has been just updated to support Xcode 12 and running from `Terminal` (see updated [ReadMe](https://github.com/devMEremenko/XcodeBenchmark))

Could you please rerun your tests with the latest version of XcodeBenchmark and ensure you attached all necessary information described in the [Contribution](https://github.com/devMEremenko/XcodeBenchmark#contribution) section.

Thanks

**Comment by owenzhao** [comment]
<img width="682" alt="截屏2020-11-18 上午11 49 46" src="https://user-images.githubusercontent.com/2182896/99480997-29e98300-2994-11eb-8fae-73c1db1249a5.png">

iMac 5K 2014 late i7 4790K.
