### ISSUE TITLE
Instructions for command line build

### ISSUE THREAD

**Issue by Pe-te** [devMEremenko/XcodeBenchmark#24]
Would be great if you can add a small bash script that runs the build from the command line. I had to stumble through "workspace, not project", then the wrong scheme was selected. Maybe even collect all the information you need to populate the table?

Will try to measure the performance once my machine is not under heavy load .. so probably around christmas! :-D

**Comment by devMEremenko** [comment]
Hi @Pe-te,

Thank you for the suggestion.

XcodeBenchmark has been just updated to support Xcode 12 and running from `Terminal` (see updated [ReadMe](https://github.com/devMEremenko/XcodeBenchmark))
