### ISSUE TITLE
List of results 

### ISSUE THREAD

**Issue by bitsmakerde** [devMEremenko/XcodeBenchmark#3]
Hi,

it is possible to store a results list from all tested devices? So I can compare it with my system or wish system?

Thank you

**Comment by devMEremenko** [comment]
Hi @bitsmakerde,

Thank you for raising this.

I've just updated ReadMe with the [Score](https://github.com/devMEremenko/XcodeBenchmark#score) and [Contribution](https://github.com/devMEremenko/XcodeBenchmark#score) sections.

**Comment by bitsmakerde** [comment]
great Thank you.

I have this result for my Mac book.

MacBook Pro 16" 2019
i9 2,3 GHz 8-core
RAM 32 GB
SSD 2 TB
Xcode 11.6
MacOS 10.15.6
Time: 328s

**Comment by devMEremenko** [comment]
Thank you for sharing. Your result is added 👍
