### ISSUE TITLE
Fails to build in Xcode 14

### ISSUE THREAD

**Issue by MDStebel** [devMEremenko/XcodeBenchmark#354]
When building in Xcode 14, the following error is generated: 

error: Signing for "gRPC-C++-gRPCCertificates-Cpp" requires a development team. Select a development team in the Signing & Capabilities editor. (in target 'gRPC-C++-gRPCCertificates-Cpp' from project 'Pods')
** BUILD FAILED **

System Version: 12.6
Xcode 14.0
Hardware Overview
      Model Name: MacBook Pro
      Model Identifier: MacBookPro18,4
      Total Number of Cores: 10 (8 performance and 2 efficiency)

**Comment by 1987zcc** [comment]
/Volumes/Work/Github/XcodeBenchmark/Pods/Pods.xcodeproj: error: Signing for "gRPC-C++-gRPCCertificates-Cpp" requires a development team. Select a development team in the Signing & Capabilities editor. (in target 'gRPC-C++-gRPCCertificates-Cpp' from project 'Pods')
** BUILD FAILED **

System Version: 12.5.1
Xcode 14.0
Hardware Overview
      Model Name: MacBook Air
      Model Identifier: MacBookAir10,1
      Total Number of Cores: 8 (4 performance and 4 efficiency)
      Memory: 16 GB

✅ XcodeBenchmark has completed
1️⃣  Take a screenshot of this window (Cmd + Shift + 4 + Space) and resize to include:
	- Build Time (See ** BUILD SUCCEEDED ** [XYZ sec])
	- System Version
	- Xcode Version
	- Hardware Overview
	- Started 00:12:06
	- Ended   00:12:12
	- Date 2022年 9月17日 星期六 00时12分12秒 CST

2️⃣  Share your results at https://github.com/devMEremenko/XcodeBenchmark

**Comment by grx7** [comment]
it won't build. Download 13.4 https://developer.apple.com/download/all/?q=Xcode  it'll build it fine
