### ISSUE TITLE
Hackintosh i5-8400 

### ISSUE THREAD

**Issue by ivanfeanor** [devMEremenko/XcodeBenchmark#4]
Hi, i run this test on my hackintosh, here is the results, if you plan to add hack's into the chart. 
|        Device        |         CPU         | RAM | SSD | Xcode |  macOS  | Time(sec) |
|:--------------------:|:-------------------:|:---:|:---:|:-----:|:-------:|:---------:|
| Hackintosh i5-8400   |  i5 2,8 Ghz 6-core  |  32 | 512 |  11.6 | 10.15.6 |    409    |

**Comment by devMEremenko** [comment]
Hi @ivanfeanor, I think it's worth adding. Thank you!
