### ISSUE TITLE
SSD-Type

### ISSUE THREAD

**Issue by Pe-te** [devMEremenko/XcodeBenchmark#43]
Hi, just did the benchmark on my old 2015 mac book pro.

Can't really disable Avira, so I just did a build with wifi on and no cooldown, best do not use my results.

The build was still finished in 366 seconds, compared to the 594 seconds of the same macbook model in the table.

Xcode and MacOS are newer, okay, but I think the difference comes from a recent hard disk upgrade?
Instead of the original apple SSD I have a newer model now (Aura Pro X2, 480 GB).

Table: MacBook Pro 15" 2015 | i7 2.2 GHz 4-core | 16 | 265 |   | 11.7 | 10.15.6 | 594
Mine: MacBook Pro 15" 2015 | i7 2.2 GHz 4-core | 16 | 512 |   | 12.2 | 11.0.1 | 366

Maybe it makes sense to add a column for the type of hard disk?

<img width="686" alt="withavira" src="https://user-images.githubusercontent.com/7301171/99517331-88603280-298f-11eb-9862-ce8b31caaf9d.png">

**Comment by mikehouse** [comment]
The same, I use ram memory mapped to a separate volume for my projects source code and Xcode's derived data, and difference is huge, 235 seconds on built in hard drive (Fusion drive) vs. 175 seconds on ram volume.

**Comment by Pe-te** [comment]
> The same, I use ram memory mapped to a separate volume for my projects ...

Wow, I haven't heard those words for around 25 years now .. great idea, will give it a try! 🥳

**Comment by devMEremenko** [comment]
Hi @Pe-te,

Thank you for the suggestion. I agree that type of a storage matter.

I added a comment to the `Contribution` section:
> if you have any non-Apple hardware components - submit your results to the `Custom Hardware` table.

And `Comments` column to the `Custom Hardware` table.

**Comment by devMEremenko** [comment]
Hi @mikehouse, 

I tried ram storage for Derived Data (but not for projects because there is no guarantee that your work will be saved), and I think it's a great speed up for HDD, but there is almost no difference if you use SSD. Moreover, it might add additional overhead for OS to move your data to/from disk if there is not enough free memory.

**Comment by mikehouse** [comment]
Hello @devMEremenko,
I agree when there is ssd no needs to use ram volume at all. My workstation mac mini at the company's office has fast nvme ssd I don't see any differences vs. ram at my home iMac (fusion drive 1 TB). But I see a lot of speed improvements on hdd iMac for my work flow when moved all apps (AppCode, VSCode, ... except Xcode as it is too big ))) ) and projects there. For projects syncing I use rsync cron task. When there not enough memory I just redo volume with new size, I cannot utilize all 64 GB memory anyway even with ram volume.

**Comment by devMEremenko** [comment]
@mikehouse, thank you for sharing your experience 👍

**Comment by devMEremenko** [comment]
@Pe-te, it looks like the original problem is solved. I am closing the issue. 

Feel free to open it again if you have any suggestions.
