### ISSUE TITLE
MacBook Air 2020 (M1, 16GB RAM)

### ISSUE THREAD

**Issue by twlatl** [devMEremenko/XcodeBenchmark#44]
** BUILD SUCCEEDED ** [127.713 sec]

System Version: 11.0.1
Xcode 12.2
Hardware Overview
      Model Name: MacBook Air
      Model Identifier: MacBookAir10,1
      Total Number of Cores: 8 (4 performance and 4 efficiency)
      Memory: 16 GB

✅ XcodeBenchmark has completed
1️⃣  Take a screenshot of this window (Cmd + Shift + 4 + Space) and resize to include:
	- Build Time (See ** BUILD SUCCEEDED ** [XYZ sec])
	- System Version
	- Xcode Version
	- Hardware Overview
	- Started 07:55:43
	- Ended   07:57:54
	- Date Wed Nov 18 07:57:54 EST 2020

[
<img width="961" alt="Screen Shot 2020-11-18 at 8 04 56 AM" src="https://user-images.githubusercontent.com/110389/99534283-2abeec80-2975-11eb-9bba-8b2fd6be5801.png">
](url)

**Comment by devMEremenko** [comment]
Hi @twlatl,

Thank you for your contribution.

What is the size of the SSD?

**Comment by twlatl** [comment]
512GB

**Comment by devMEremenko** [comment]
@twlatl, one more question: How many GPU-cores do you have? 7 or 8?

**Comment by devMEremenko** [comment]
@twlatl, can I ask you to perform the following commands in `Terminal` and share a result?

`system_profiler SPSerialATADataType`
`system_profiler SPHardwareDataType`

You can exclude a serial number, etc

1. I noticed that there is no information about SSD.
2. It might be a measurement error, but [MacBook Pro 13" (M1, 16 RAM)](https://github.com/devMEremenko/XcodeBenchmark/pull/34) runs a bit slower (with the active cooling system). Possibly, it will help to understand a reason.

**Comment by twlatl** [comment]
8

**Comment by twlatl** [comment]
➜  Documents system_profiler SPSerialATADataType
➜  Documents system_profiler SPHardwareDataType
Hardware:

    Hardware Overview:

      Model Name: MacBook Air
      Model Identifier: MacBookAir10,1
      Chip: Apple M1
      Total Number of Cores: 8 (4 performance and 4 efficiency)
      Memory: 16 GB
      System Firmware Version: 6723.50.2
      Serial Number (system):
      Hardware UUID: 501D39AA-92D3-5ACC-A5F0-24153CFDD562
      Provisioning UDID: 00008103-001E70D63EA2001E
      Activation Lock Status: Enabled

**Comment by devMEremenko** [comment]
Thank you, I added a result
