### ISSUE TITLE
MacBook Pro 16" 2019 (i9/64GB RAM)

### ISSUE THREAD

**Issue by twlatl** [devMEremenko/XcodeBenchmark#45]
** BUILD SUCCEEDED ** [223.016 sec]

System Version: 11.0.1
Xcode 12.2
Hardware Overview
      Model Name: MacBook Pro
      Model Identifier: MacBookPro16,1
      Processor Name: 8-Core Intel Core i9
      Processor Speed: 2.4 GHz
      Total Number of Cores: 8
      L2 Cache (per Core): 256 KB
      L3 Cache: 16 MB
      Number of Processors: 1
      Hyper-Threading Technology: Enabled
      Memory: 64 GB

✅ XcodeBenchmark has completed
1️⃣  Take a screenshot of this window (Cmd + Shift + 4 + Space) and resize to include:
	- Build Time (See ** BUILD SUCCEEDED ** [XYZ sec])
	- System Version
	- Xcode Version
	- Hardware Overview
	- Started 07:59:28
	- Ended   08:03:18
	- Date Wed Nov 18 08:03:18 EST 2020
<img width="1012" alt="Screen Shot 2020-11-18 at 8 09 37 AM" src="https://user-images.githubusercontent.com/110389/99534493-7a9db380-2975-11eb-9e46-9342e2be0ea7.png">

**Comment by devMEremenko** [comment]
Hi @twlatl,

What is the SSD size?

**Comment by twlatl** [comment]
512GB

**Comment by twlatl** [comment]
4TB

**Comment by devMEremenko** [comment]
I added a result
