### ISSUE TITLE
Failed to build with Xcode 16

### ISSUE THREAD

**Issue by Leofeng527** [devMEremenko/XcodeBenchmark#513]
Hello,
I got an error when I executed this tool with Xcode 16 on Sequoia. And I have searched some information relevant to the error. Maybe some dependencies need to be updated to support Xcode 16.

**error:**
clang: error: unsupported option '-G' for target
      'arm64-apple-ios14.5'

**Comment by devMEremenko** [comment]
Thank you for the report. Fixed
