### ISSUE TITLE
Build Failure with BoringSSL-RPC

### ISSUE THREAD

**Issue by polanfong** [devMEremenko/XcodeBenchmark#514]
System Version: 14.4
Xcode 15.4
Hardware Overview
      Model Name: MacBook Pro
      Model Identifier: Mac15,7
      Total Number of Cores: 12 (6 performance and 6 efficiency)
      Memory: 36 GB

Build results in a few of these error messages:
```
error: unsupported option '-G' for target 'arm64-apple-ios14.5' (in target 'BoringSSL-GRPC' from project 'Pods')
```

Summary of build failures:
```
The following build commands failed:
ScanDependencies /XcodeBenchmark-master/DerivedData/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/BoringSSL-GRPC.build/Objects-normal/arm64/x_val.o /Users/polanfong/Downloads/XcodeBenchmark-master/Pods/BoringSSL-GRPC/src/crypto/x509/x_val.c normal arm64 c com.apple.compilers.llvm.clang.1_0.compiler (in target 'BoringSSL-GRPC' from project 'Pods')

ScanDependencies /XcodeBenchmark-master/DerivedData/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/BoringSSL-GRPC.build/Objects-normal/arm64/x_x509a.o /Users/polanfong/Downloads/XcodeBenchmark-master/Pods/BoringSSL-GRPC/src/crypto/x509/x_x509a.c normal arm64 c com.apple.compilers.llvm.clang.1_0.compiler (in target 'BoringSSL-GRPC' from project 'Pods')

ScanDependencies /XcodeBenchmark-master/DerivedData/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/BoringSSL-GRPC.build/Objects-normal/arm64/x_x509.o /Users/polanfong/Downloads/XcodeBenchmark-master/Pods/BoringSSL-GRPC/src/crypto/x509/x_x509.c normal arm64 c com.apple.compilers.llvm.clang.1_0.compiler (in target 'BoringSSL-GRPC' from project 'Pods')

CompileC /XcodeBenchmark-master/DerivedData/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/BoringSSL-GRPC.build/Objects-normal/arm64/tls_record.o /Users/polanfong/Downloads/XcodeBenchmark-master/Pods/BoringSSL-GRPC/src/ssl/tls_record.cc normal arm64 c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'BoringSSL-GRPC' from project 'Pods')

CompileC /XcodeBenchmark-master/DerivedData/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/BoringSSL-GRPC.build/Objects-normal/arm64/tls_method.o /Users/polanfong/Downloads/XcodeBenchmark-master/Pods/BoringSSL-GRPC/src/ssl/tls_method.cc normal arm64 c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'BoringSSL-GRPC' from project 'Pods')
```

I've tried the solution from https://stackoverflow.com/questions/78608693/boringssl-grpc-unsupported-option-g-for-target-arm64-apple-ios15-0 but that didn't resolve the issue.

**Comment by ilsinszkibal** [comment]
I've had the same issues with Xcode 16.0 and found the solution [here](https://github.com/grpc/grpc/pull/36904#issuecomment-2174416688)

Change the bottom of the pod file to:
`post_install do |pi|
    pi.pods_project.targets.each do |t|
        if t.name == 'BoringSSL-GRPC'
            t.source_build_phase.files.each do |file|
                if file.settings && file.settings['COMPILER_FLAGS']
                    flags = file.settings['COMPILER_FLAGS'].split
                    flags.reject! { |flag| flag == '-GCC_WARN_INHIBIT_ALL_WARNINGS' }
                    file.settings['COMPILER_FLAGS'] = flags.join(' ')
                end
            end
        end

        t.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = minimum_target
            config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'

            xcconfig_path = config.base_configuration_reference.real_path
            xcconfig = File.read(xcconfig_path)
            xcconfig_mod = xcconfig.gsub(/DT_TOOLCHAIN_DIR/, "TOOLCHAIN_DIR")
            File.open(xcconfig_path, "w") { |file| file << xcconfig_mod }
        end
    end
end`

Run `pod install --no-repo-update` and run the benchmark script again:

<img width="1324" alt="Screenshot 2024-10-11 at 23 57 27" src="https://github.com/user-attachments/assets/c02bf34d-011a-4cca-9b80-43a8dc270aae">

**Comment by devMEremenko** [comment]
@ilsinszkibal, thank you, I've updated the project

**Comment by SevkiBekir** [comment]
Thank you!

I added `BoringSSL-GRPC` part into post_install, then build is succeeded in react native

```
   installer.pods_project.targets.each do |t|
      if t.name == 'BoringSSL-GRPC'
          t.source_build_phase.files.each do |file|
              if file.settings && file.settings['COMPILER_FLAGS']
                  flags = file.settings['COMPILER_FLAGS'].split
                  flags.reject! { |flag| flag == '-GCC_WARN_INHIBIT_ALL_WARNINGS' }
                  file.settings['COMPILER_FLAGS'] = flags.join(' ')
              end
          end
      end
    end
```
