### ISSUE TITLE
Vk SDK Resources error in Xcode 11.7

### ISSUE THREAD

**Issue by radianttap** [devMEremenko/XcodeBenchmark#7]
/XcodeBenchmark/Pods/VK-ios-sdk/library/Resources/SdkAssetCatalog.xcassets:1:1: 
Failed to find a suitable device for the type IBSimDeviceTypeiPad2x (com.apple.dt.Xcode.IBSimDeviceType.iPad-2x) with runtime iOS 13.7 (13.7 - 17H22) - com.apple.CoreSimulator.SimRuntime.iOS-13-7

Never seen such an error before, not sure what it refers to.

**Comment by radianttap** [comment]
Ugh, apparently this message is shown when CoreSimulatorService crashes repeatedly. Wonderful. This is solution:

`sudo killall -9 com.apple.CoreSimulator.CoreSimulatorService`

**Comment by MrBoog** [comment]
Nice, you save my life
