### ISSUE TITLE
MBA 2014 results

### ISSUE THREAD

**Issue by sahilsatralkar** [devMEremenko/XcodeBenchmark#75]
Device        |           CPU           | RAM | SSD | HDD | Xcode |  macOS  | Time(sec) |    Comments    |
|:--------------------:|:-----------------------:|:---:|:---:|:---:|:-----:|:-------:|:---------:|----------------|
|     MacBook Air 2014     |  i5 1.4 GHz 2-core   |  4 | 128 |     |  12.2 | 11.0.1  |    894     |                |

![Screenshot 2020-11-24 at 12 48 30 PM](https://user-images.githubusercontent.com/62758655/100065784-38cfaa00-2e5a-11eb-8d0f-deb126f610cc.png)

**Comment by devMEremenko** [comment]
Hi @sahilsatralkar, the result is merged
